# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: "Validate Pull Request"

on:
  push:
    branches: [ main, dev, feat/kiota-preview ]
  pull_request:
    branches: [ main, dev, feat/kiota-preview ]

defaults:
  run:
    shell: bash

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer file
      run: |
        composer validate
    - name: Install dependencies
      run: |
        composer install -a
    - name: run tests
      run : |
        vendor/bin/phpunit --coverage-text
    - name: Run static analysis
      run: |
        vendor/bin/phpstan analyse --memory-limit=8G --error-format=github
